$('head').append(
    '<style>body{display:none;}',
    '<style>#load1{display:none;}',
    '<style>#load2{display:none;}',
    '<style>#load3{display:none;}',
    '<style>#load4{display:none;}',
    '<style>#load5{display:none;}',
    '<style>#load6{display:none;}',
    '<style>#load7{display:none;}',
    '<style>#load8{display:none;}',
    '<style>#load9{display:none;}',
    '<style>#load10{display:none;}',
    '<style>#load11{display:none;}',
    '<style>#load12{display:none;}',
    '<style>#load13{display:none;}',
    '<style>#load_a{display:none;}',
    '<style>#load_b{display:none;}',
    '<style>#load_c{display:none;}',
);
$(window).on("load", function() {
    $('body').delay(150).fadeIn("slow");
    $('#load1').delay(200).fadeIn("slow");
    $('#load2').delay(250).fadeIn("slow");
    $('#load3').delay(300).fadeIn("slow");
    $('#load4').delay(350).fadeIn("slow");
    $('#load5').delay(400).fadeIn("slow");
    $('#load6').delay(450).fadeIn("slow");
    $('#load7').delay(700).fadeIn("slow");
    $('#load8').delay(750).fadeIn("slow");
    $('#load9').delay(800).fadeIn("slow");
    $('#load10').delay(850).fadeIn("slow");
    $('#load11').delay(900).fadeIn("slow");
    $('#load12').delay(950).fadeIn("slow");
    $('#load13').delay(1000).fadeIn("slow");
    $('#load_a').delay(1500).fadeIn("slow");
    $('#load_b').delay(2000).fadeIn("slow");
    $('#load_c').delay(2500).fadeIn("slow");
});
$('.profile').on('click', function(){
    $('.profile').toggleClass('is-active');
});